{
 "title": "CacheBench Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cb_workload", "label": "CacheBench Workload ID", "query": { "query": "get" } },
   {
    "name": "cb_metrics",
    "label": "CacheBench Metrics",
    "query": "ItemsinRAM,ItemsinNVM,AllocAttempts,RAMEvictions,Tier0BackgroundEvicteditems,Tier0BackgroundEvicteditemsfromschedule,Tier0BackgroundTraversals,Tier0TotalClasses,Tier0BackgroundEvictedSize,CacheGets,HitRatio,CacheFindAPIlatencyp50,CacheFindAPIlatencyp90,CacheFindAPIlatencyp99,CacheFindAPIlatencyp999,CacheFindAPIlatencyp9999,CacheFindAPIlatencyp99999,CacheFindAPIlatencyp999999,CacheFindAPIlatencyp100,CacheAllocateAPIlatencyp50,CacheAllocateAPIlatencyp90,CacheAllocateAPIlatencyp99,CacheAllocateAPIlatencyp999,CacheAllocateAPIlatencyp9999,CacheAllocateAPIlatencyp99999,CacheAllocateAPIlatencyp999999,CacheAllocateAPIlatencyp100,NVMGets,NVMPuts,NVMEvicts,NVMDeletes,CacheGets_HRStats,HitRatio_HRStats,RAMHitRatio,NVMHitRatio,TotalOps,Totalsets,get,set,del"
   },
   { "name": "host_ip", "label": "Host IP", "query": { "query": "pool_total_size" } }
  ]
 },
 "panels": [
  { "title": "Panel Title", "type": "volkovlabs-form-panel", "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 } },
  { "title": "CacheBench", "type": "cloudspout-button-panel", "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 } },
  {
   "title": "CacheBench",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 11 },
   "options": {
    "content": "# Config 1\n\nSome description of the config"
   }
  },
  {
   "title": "CacheBench",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 11 },
   "options": {
    "content": "# Config 2\n\nSome description of the config"
   }
  },
  {
   "title": "CacheBench",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 11 },
   "options": {
    "content": "# Config 3\n\nSome description of the config"
   }
  },
  { "title": "CacheBench", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 } },
  { "title": "CacheBench", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 4, "x": 4, "y": 19 } },
  { "title": "CacheBench", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 4, "x": 8, "y": 19 } },
  {
   "title": "Tier 0 Background Evictions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Tier0BackgroundTraversals/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(Tier0BackgroundTraversals[4s])",
     "legendFormat": "Tier0BackgroundTraversals/s - {{workload}}"
    }
   ]
  },
  {
   "title": "Cachebench metrics (Workload ID: $cb_workload)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$cb_metrics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "repeat": "cb_metrics",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "$cb_metrics", "legendFormat": "{{workload}}" }
   ]
  },
  {
   "title": "Ram Eviction Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "targets": [
    { "expr": "irate(RAMEvictions[2s])", "legendFormat": "{{workload}}" }
   ]
  }
 ]
}