
PCM_SENSOR_SERVER_IP=
PUSHGATEWAY_SERVER_IP=
GRAFANA_PORT=
CONTROL_SERVER_IP=

PCM_SERVER_PORT=$(echo $PCM_SENSOR_SERVER_IP | cut -d ":" -f 2)
PUSHGATEWAY_PORT=$(echo $PUSHGATEWAY_SERVER_IP | cut -d ":" -f 2)
CONTROL_PORT=$(echo $CONTROL_SERVER_IP | cut -d ":" -f 2)
HOST_PUBLIC_IP=$(hostname -I | awk '{print $1}')
GRAFNA_SERVER_IP=$HOST_PUBLIC_IP:$GRAFANA_PORT
